"""
backend/report_generator.py
============================
Generates professional PDF medical reports for high-risk AI predictions.

Uses fpdf2 (pure Python, no external binary needed).
Install: pip install fpdf2

Output: reports_output/{user_id}/AarogyaAI_Report_{pred_id}.pdf
"""

import json
import os
from datetime import datetime
from pathlib import Path

from fpdf import FPDF, XPos, YPos

REPORTS_DIR = Path("reports_output")
LOGO_PATH   = Path("assets/logo.png")   # optional — skipped if not found

# ── Brand colours (RGB) ──────────────────────────────────────────────────────
TEAL        = (29, 158, 117)
DARK_TEAL   = (15, 110, 86)
RED         = (163, 45,  45)
ORANGE      = (220, 120, 40)
DARK        = (12,  22,  38)
GRAY        = (90, 110, 130)
LIGHT_GRAY  = (240, 244, 248)
WHITE       = (255, 255, 255)
BLACK       = (30,  30,  30)

RISK_COLOUR = {
    "low":      TEAL,
    "moderate": ORANGE,
    "high":     RED,
}

DISEASE_DISPLAY = {
    "blood_cell_cancer": "Blood Cell Cancer (ALL)",
    "heart_disease":     "Heart Disease",
    "lung_cancer":       "Lung Cancer",
    "parkinsons":        "Parkinson's Disease",
    "thyroid":           "Thyroid Disorder",
    "diabetes":          "Diabetes",
}

DISEASE_ADVICE = {
    "blood_cell_cancer": (
        "Acute Lymphoblastic Leukemia (ALL) is a rapidly progressing cancer of the blood and "
        "bone marrow. Immediate consultation with a haematologist or oncologist is strongly "
        "advised. Treatment typically includes chemotherapy, targeted therapy, and in some "
        "cases bone marrow transplantation."
    ),
    "heart_disease": (
        "Elevated cardiovascular risk has been identified. Please consult a cardiologist "
        "without delay. Key interventions include lifestyle modifications (diet, exercise, "
        "smoking cessation), medication management, and regular cardiac monitoring."
    ),
    "lung_cancer": (
        "Several lung cancer risk factors were detected. Early-stage lung cancer has "
        "significantly better outcomes. Please schedule a CT scan and consult a pulmonologist "
        "or thoracic oncologist promptly."
    ),
    "parkinsons": (
        "Vocal biomarker analysis suggests Parkinson's Disease characteristics. A neurologist "
        "should perform comprehensive clinical assessment including MRI and dopaminergic imaging. "
        "Early treatment can substantially slow disease progression."
    ),
    "thyroid": (
        "Thyroid dysfunction was detected. This is a treatable condition. Please consult an "
        "endocrinologist for full thyroid function evaluation including TSH, T3, T4, and "
        "thyroid antibody tests, plus ultrasound if indicated."
    ),
    "diabetes": (
        "Elevated diabetes risk identified. Please consult an endocrinologist or diabetologist. "
        "Lifestyle interventions and early medication can prevent or delay Type 2 Diabetes. "
        "Schedule HbA1c and fasting glucose tests."
    ),
}

DISCLAIMER = (
    "This report was generated by AarogyaAI, an AI-powered diagnostic support tool. "
    "It is intended for informational and educational purposes only and does NOT "
    "constitute a medical diagnosis. All findings must be verified by a qualified "
    "healthcare professional before any clinical decisions are made. The AI model's "
    "predictions carry inherent uncertainty and should be interpreted alongside full "
    "clinical assessment."
)


class AarogyaAIReport(FPDF):
    """Custom FPDF subclass with branded header/footer."""

    def header(self):
        # Teal top bar
        self.set_fill_color(*DARK)
        self.rect(0, 0, 210, 18, style="F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*TEAL)
        self.set_xy(10, 4)
        self.cell(0, 10, "AarogyaAI  |  Intelligent Disease Detection & Smart Healthcare Platform", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GRAY)
        self.set_xy(0, 4)
        self.cell(w=200, h=10, text=f"CONFIDENTIAL  ·  v2.2.0", align="R")
        self.ln(14)

    def footer(self):
        self.set_y(-16)
        self.set_draw_color(*TEAL)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*GRAY)
        self.cell(0, 8,
                  f"AarogyaAI Diagnostic Report  ·  Page {self.page_no()}  ·  "
                  "Not a substitute for professional medical advice",
                  align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(*LIGHT_GRAY)
        self.set_draw_color(*TEAL)
        self.set_line_width(0.5)
        self.rect(10, self.get_y(), 190, 9, style="FD")
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*DARK_TEAL)
        self.set_xy(14, self.get_y() + 1)
        self.cell(0, 7, title.upper(), align="L")
        self.ln(12)

    def kv_row(self, key: str, value: str, shade: bool = False):
        y = self.get_y()
        if shade:
            self.set_fill_color(*LIGHT_GRAY)
            self.rect(10, y, 190, 7, style="F")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*GRAY)
        self.set_xy(14, y + 0.5)
        self.cell(60, 6, key, align="L")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*BLACK)
        self.set_xy(74, y + 0.5)
        self.cell(120, 6, str(value), align="L")
        self.ln(7)


def generate_pdf_report(prediction, user, features: dict) -> Path:
    """
    Generate a professional PDF report for a high-risk prediction.

    Args:
        prediction: Prediction ORM row
        user:       User ORM row
        features:   dict of input feature values

    Returns:
        Path to the generated PDF file.
    """
    module   = prediction.disease_module.value
    risk     = prediction.risk_level.value
    label    = prediction.result_label
    conf     = prediction.confidence
    proba    = json.loads(prediction.probabilities) if prediction.probabilities else {}
    now      = datetime.now()

    out_dir = REPORTS_DIR / str(user.id)
    out_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = out_dir / f"AarogyaAI_Report_{prediction.id}_{module}.pdf"

    pdf = AarogyaAIReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── 1. Report title block ─────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*DARK)
    pdf.set_xy(10, 22)
    pdf.cell(0, 12, "Medical Diagnostic Report", align="C")
    pdf.ln(14)

    # Risk badge
    r_colour = RISK_COLOUR.get(risk, GRAY)
    pdf.set_fill_color(*r_colour)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 12)
    badge_w = 80
    badge_x = (210 - badge_w) / 2
    pdf.set_xy(badge_x, pdf.get_y())
    pdf.cell(badge_w, 10, f"  RISK LEVEL: {risk.upper()}  ", align="C",
             fill=True, border=0)
    pdf.ln(14)

    # ── 2. Report metadata ────────────────────────────────────────────────────
    pdf.section_title("Report Information")
    pdf.kv_row("Report ID",       f"MR-{prediction.id:06d}",                  shade=False)
    pdf.kv_row("Generated on",    now.strftime("%d %B %Y, %H:%M"),            shade=True)
    pdf.kv_row("Disease module",  DISEASE_DISPLAY.get(module, module),        shade=False)
    pdf.kv_row("Model version",   prediction.model_version or "2.2.0",        shade=True)
    pdf.kv_row("Inference time",  f"{prediction.inference_ms:.1f} ms" if prediction.inference_ms else "—",
               shade=False)

    # ── 3. Patient information ────────────────────────────────────────────────
    pdf.section_title("Patient Information")
    pdf.kv_row("Patient name",    user.full_name,                              shade=False)
    pdf.kv_row("Email",           user.email,                                 shade=True)
    pdf.kv_row("Age",             str(user.age) if user.age else "Not provided", shade=False)
    pdf.kv_row("Gender",          user.gender or "Not provided",              shade=True)
    pdf.kv_row("Blood group",     user.blood_group or "Not provided",         shade=False)
    pdf.kv_row("Phone",           user.phone or "Not provided",               shade=True)

    # ── 4. AI prediction result ───────────────────────────────────────────────
    pdf.section_title("AI Prediction Result")

    # Highlighted result box
    pdf.set_fill_color(*r_colour)
    pdf.set_draw_color(*r_colour)
    pdf.set_line_width(0.3)
    box_y = pdf.get_y()
    pdf.rect(10, box_y, 190, 22, style="FD")
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_xy(14, box_y + 3)
    pdf.cell(0, 8, label, align="L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_xy(14, box_y + 12)
    pdf.cell(0, 7, f"Confidence: {conf:.1f}%    Risk Level: {risk.upper()}", align="L")
    pdf.ln(26)

    # Probability breakdown
    if proba:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*GRAY)
        pdf.set_xy(14, pdf.get_y())
        pdf.cell(0, 6, "CLASS PROBABILITY BREAKDOWN", align="L")
        pdf.ln(8)

        for i, (cls, pct) in enumerate(proba.items()):
            bar_y = pdf.get_y()
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*BLACK)
            pdf.set_xy(14, bar_y)
            pdf.cell(65, 5, cls, align="L")

            bar_x, bar_full_w = 80, 110
            bar_h = 4
            # Background track
            pdf.set_fill_color(220, 228, 236)
            pdf.rect(bar_x, bar_y + 0.5, bar_full_w, bar_h, style="F")
            # Filled portion
            colour = r_colour if pct == max(proba.values()) else TEAL
            pdf.set_fill_color(*colour)
            pdf.rect(bar_x, bar_y + 0.5, bar_full_w * pct / 100, bar_h, style="F")
            # Pct label
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*DARK)
            pdf.set_xy(bar_x + bar_full_w + 4, bar_y)
            pdf.cell(16, 5, f"{pct:.1f}%", align="R")
            pdf.ln(7)

    # ── 5. Input features ─────────────────────────────────────────────────────
    pdf.section_title("Input Features Used")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*GRAY)
    pdf.set_xy(14, pdf.get_y())
    pdf.multi_cell(182, 5,
                   "The following values were submitted for analysis. "
                   "Verify these match the patient's actual measurements.",
                   align="L")
    pdf.ln(3)

    items = list(features.items())
    col_w = 90
    for i in range(0, len(items), 2):
        shade = (i // 2) % 2 == 0
        row_y = pdf.get_y()
        if shade:
            pdf.set_fill_color(*LIGHT_GRAY)
            pdf.rect(10, row_y, 190, 6, style="F")

        k1, v1 = items[i]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*GRAY)
        pdf.set_xy(14, row_y + 0.5)
        pdf.cell(40, 5, str(k1)[:22], align="L")
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*BLACK)
        pdf.set_xy(54, row_y + 0.5)
        pdf.cell(46, 5, str(v1), align="L")

        if i + 1 < len(items):
            k2, v2 = items[i + 1]
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*GRAY)
            pdf.set_xy(104, row_y + 0.5)
            pdf.cell(40, 5, str(k2)[:22], align="L")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*BLACK)
            pdf.set_xy(144, row_y + 0.5)
            pdf.cell(46, 5, str(v2), align="L")

        pdf.ln(6)

    # ── 6. Clinical advice ────────────────────────────────────────────────────
    if risk in ("high", "moderate"):
        pdf.section_title("Clinical Advice & Recommendations")
        advice = DISEASE_ADVICE.get(module, "Please consult a qualified medical professional.")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*BLACK)
        pdf.set_xy(14, pdf.get_y())
        pdf.multi_cell(182, 5.5, advice, align="L")
        pdf.ln(4)

        # Urgency box
        urgency_colour = RED if risk == "high" else ORANGE
        pdf.set_fill_color(*urgency_colour)
        urg_y = pdf.get_y()
        pdf.rect(10, urg_y, 190, 14, style="F")
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_xy(14, urg_y + 1)
        urgency_text = (
            "⚠  URGENT: Seek specialist consultation within 48–72 hours."
            if risk == "high"
            else "ADVISORY: Schedule specialist appointment within the next 2–4 weeks."
        )
        pdf.multi_cell(182, 6, urgency_text, align="L")
        pdf.ln(16)

    # ── 7. Recommended specialists ────────────────────────────────────────────
    pdf.section_title("Recommended Specialist Type")
    specialty_map = {
        "blood_cell_cancer": ("Haematologist / Oncologist",
                              "Specialises in blood disorders and cancer treatment"),
        "heart_disease":     ("Cardiologist",
                              "Specialises in heart and cardiovascular conditions"),
        "lung_cancer":       ("Pulmonologist / Thoracic Oncologist",
                              "Specialises in lung diseases and thoracic surgery"),
        "parkinsons":        ("Neurologist",
                              "Specialises in brain and nervous system disorders"),
        "thyroid":           ("Endocrinologist",
                              "Specialises in hormone and thyroid conditions"),
        "diabetes":          ("Endocrinologist / Diabetologist",
                              "Specialises in metabolic and endocrine disorders"),
    }
    spec_name, spec_desc = specialty_map.get(module, ("General Physician", "Primary care"))
    pdf.kv_row("Specialist type", spec_name,  shade=False)
    pdf.kv_row("Description",     spec_desc,  shade=True)
    pdf.kv_row("Next steps",      "Book appointment · Bring this report · Bring all recent lab results",
               shade=False)

    # ── 8. Disclaimer ─────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Important Disclaimer")
    pdf.set_fill_color(255, 245, 230)
    disc_y = pdf.get_y()
    pdf.set_draw_color(*ORANGE)
    pdf.set_line_width(0.4)
    pdf.rect(10, disc_y, 190, 36, style="FD")
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(80, 50, 10)
    pdf.set_xy(14, disc_y + 3)
    pdf.multi_cell(182, 5.5, DISCLAIMER, align="L")
    pdf.ln(40)

    # Signature area
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*GRAY)
    sig_y = pdf.get_y()
    pdf.set_draw_color(*LIGHT_GRAY)
    pdf.set_line_width(0.3)
    pdf.line(14, sig_y + 20, 90, sig_y + 20)
    pdf.line(120, sig_y + 20, 196, sig_y + 20)
    pdf.set_xy(14, sig_y + 22)
    pdf.cell(76, 5, "Patient signature / date", align="C")
    pdf.set_xy(120, sig_y + 22)
    pdf.cell(76, 5, "Physician signature / stamp", align="C")

    # Save
    pdf.output(str(pdf_path))
    print(f"[Report] Generated: {pdf_path}")
    return pdf_path